[package]
name = "riti"
version = "0.1.0"
authors = ["Muhammad Mominul Huque <mominul2082@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["staticlib"]

[dependencies]
serde_json = "1.0"
regex = "1.0"
stringplus = "0.1"
rustc-hash = "1.0"
lazy_static = "1.0"
edit-distance = "2.0"
rupantor = "0.2"
rayon = "1.0"
hashbrown = { version = "0.4", features = ["rayon", "serde"] }
